//! Tray login autostart sync (XDG `.desktop` under `autostart/`).

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use walls_core::apply::Desktop;
use walls_core::autostart::{
    autostart_desktop_file_path, autostart_out_of_sync, build_autostart_desktop_entry,
    desktop_config_key, enabled_autostart_only_show_in, sync_tray_autostart_with,
    AutostartSyncOpts,
};
use walls_core::config::{Config, TrayAutostartConfig, TrayConfig};

fn minimal_config(autostart: TrayAutostartConfig) -> Config {
    serde_json::from_value(serde_json::json!({
        "paths": {
            "cache_dir": "cache",
            "download_dir": "downloaded",
            "favorites_dir": "favorites",
            "fetched_dir": "fetched",
            "compose_dir": "wallpaper"
        },
        "tray": {
            "accent": "blue",
            "autostart": autostart
        }
    }))
    .expect("config")
}

fn sync_opts<'a>(
    config_home: &'a std::path::Path,
    tray_bin: PathBuf,
    config: &'a Config,
) -> AutostartSyncOpts<'a> {
    AutostartSyncOpts {
        config_home,
        tray_bin,
        config,
        xdg_current_desktop: None,
        xdg_session_desktop: None,
        desktop_startup_id: None,
        xdg_session_type: Some("wayland"),
        wayland_display: Some("wayland-1"),
        display: None,
    }
}

#[test]
fn desktop_config_key_maps_known_desktops() {
    assert_eq!(desktop_config_key(Desktop::Cosmic), "cosmic");
    assert_eq!(desktop_config_key(Desktop::Kde), "kde");
    assert_eq!(desktop_config_key(Desktop::Gnome), "gnome");
}

#[test]
fn enabled_only_show_in_skips_unsupported_desktops() {
    let mut desktops = HashMap::new();
    desktops.insert("kde".into(), true);
    desktops.insert("awesome".into(), true);
    desktops.insert("gnome".into(), false);

    let only_show_in = enabled_autostart_only_show_in(&desktops);
    assert_eq!(only_show_in, vec!["KDE"]);
}

#[test]
fn build_entry_includes_exec_and_only_show_in() {
    let entry = build_autostart_desktop_entry("/usr/bin/walls-tray", &["KDE", "COSMIC"]);
    assert!(entry.contains("Exec=/usr/bin/walls-tray"));
    assert!(entry.contains("OnlyShowIn=KDE;COSMIC;"));
    assert!(entry.contains("X-GNOME-Autostart-enabled=true"));
    assert!(entry.contains("Generated by walls"));
}

#[test]
fn sync_writes_autostart_file_when_desktop_enabled() {
    let root = tempfile::tempdir().expect("tempdir");
    let config_home = root.path().join("config");
    let tray_bin = root.path().join("walls-tray");
    fs::write(&tray_bin, b"tray").expect("tray bin");

    let mut desktops = HashMap::new();
    desktops.insert("kde".into(), true);
    let config = minimal_config(TrayAutostartConfig { desktops });

    let opts = sync_opts(&config_home, tray_bin, &config);
    sync_tray_autostart_with(&opts).expect("sync");

    let path = autostart_desktop_file_path(&config_home);
    let text = fs::read_to_string(&path).expect("autostart file");
    assert!(text.contains("Exec="));
    assert!(text.contains("OnlyShowIn=KDE;"));
}

#[test]
fn sync_removes_autostart_file_when_all_desktops_disabled() {
    let root = tempfile::tempdir().expect("tempdir");
    let config_home = root.path().join("config");
    let tray_bin = root.path().join("walls-tray");
    fs::write(&tray_bin, b"tray").expect("tray bin");

    let autostart_path = autostart_desktop_file_path(&config_home);
    fs::create_dir_all(autostart_path.parent().expect("parent")).expect("mkdir");
    fs::write(
        &autostart_path,
        build_autostart_desktop_entry("/old/walls-tray", &["KDE"]),
    )
    .expect("seed");

    let config = minimal_config(TrayAutostartConfig {
        desktops: HashMap::new(),
    });

    let opts = sync_opts(&config_home, tray_bin, &config);
    sync_tray_autostart_with(&opts).expect("sync");
    assert!(!autostart_path.exists());
}

#[test]
fn autostart_out_of_sync_detects_missing_file() {
    let root = tempfile::tempdir().expect("tempdir");
    let config_home = root.path().join("config");
    let tray_bin = root.path().join("walls-tray");
    fs::write(&tray_bin, b"tray").expect("tray bin");

    let mut desktops = HashMap::new();
    desktops.insert("cosmic".into(), true);
    let config = minimal_config(TrayAutostartConfig { desktops });

    let opts = sync_opts(&config_home, tray_bin, &config);
    assert!(autostart_out_of_sync(&opts));
}

#[test]
fn tray_config_defaults_to_empty_autostart_map() {
    let config: TrayConfig = serde_json::from_str(r#"{"accent":"blue"}"#).expect("tray config");
    assert!(config.autostart.desktops.is_empty());
}
