//! Sync tray login autostart via XDG `autostart/*.desktop`.

use std::collections::HashMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use crate::apply::{detect_desktop, Desktop};
use crate::bin_resolve::{resolve_binary, BinResolveOpts};
use crate::config::Config;
use crate::tray::{session_type_from_env, unsupported_tray_reason};

const AUTOSTART_FILENAME: &str = "walls-tray.desktop";
const GENERATED_MARKER: &str = "Generated by walls";

/// Inputs for [`sync_tray_autostart_with`] (testable).
#[derive(Debug, Clone)]
pub struct AutostartSyncOpts<'a> {
    pub config_home: &'a Path,
    pub tray_bin: PathBuf,
    pub config: &'a Config,
    pub xdg_current_desktop: Option<&'a str>,
    pub xdg_session_desktop: Option<&'a str>,
    pub desktop_startup_id: Option<&'a str>,
    pub xdg_session_type: Option<&'a str>,
    pub wayland_display: Option<&'a str>,
    pub display: Option<&'a str>,
}

/// Outcome of syncing tray autostart.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AutostartSyncOutcome {
    Written,
    Removed,
    WouldWrite { path: PathBuf },
    WouldRemove { path: PathBuf },
    Skipped { reason: String },
}

/// Config key for a [`Desktop`] in `tray.autostart.desktops`.
pub fn desktop_config_key(desktop: Desktop) -> &'static str {
    match desktop {
        Desktop::Cosmic => "cosmic",
        Desktop::Gnome => "gnome",
        Desktop::Unity => "unity",
        Desktop::Budgie => "budgie",
        Desktop::Kde => "kde",
        Desktop::Xfce => "xfce",
        Desktop::Lxde => "lxde",
        Desktop::Lxqt => "lxqt",
        Desktop::Mate => "mate",
        Desktop::Cinnamon => "cinnamon",
        Desktop::Deepin => "deepin",
        Desktop::Sway => "sway",
        Desktop::Hyprland => "hyprland",
        Desktop::Enlightenment => "enlightenment",
        Desktop::Awesome => "awesome",
        Desktop::Fluxbox => "fluxbox",
        Desktop::Trinity => "trinity",
        Desktop::Lingmo => "lingmo",
        Desktop::Unknown => "unknown",
    }
}

/// `OnlyShowIn` token for a supported desktop.
pub fn desktop_only_show_in(desktop: Desktop) -> &'static str {
    match desktop {
        Desktop::Cosmic => "COSMIC",
        Desktop::Gnome => "GNOME",
        Desktop::Unity => "Unity",
        Desktop::Budgie => "Budgie",
        Desktop::Kde => "KDE",
        Desktop::Xfce => "XFCE",
        Desktop::Lxde => "LXDE",
        Desktop::Lxqt => "LXQt",
        Desktop::Mate => "MATE",
        Desktop::Cinnamon => "Cinnamon",
        Desktop::Deepin => "Deepin",
        Desktop::Sway => "sway",
        Desktop::Hyprland => "Hyprland",
        Desktop::Enlightenment => "Enlightenment",
        Desktop::Awesome => "awesome",
        Desktop::Fluxbox => "Fluxbox",
        Desktop::Trinity => "Trinity",
        Desktop::Lingmo => "Lingmo",
        Desktop::Unknown => "X-GNOME-Autostart-Phase",
    }
}

/// Whether tray autostart can be configured on this desktop.
pub fn tray_autostart_available(desktop: Desktop) -> bool {
    unsupported_tray_reason(desktop).is_none()
}

/// Read per-desktop autostart flag from config.
pub fn tray_autostart_enabled_for_desktop(config: &Config, desktop: Desktop) -> bool {
    config
        .tray
        .autostart
        .desktops
        .get(desktop_config_key(desktop))
        .copied()
        .unwrap_or(false)
}

/// Set per-desktop autostart flag in config.
pub fn set_tray_autostart_for_desktop(config: &mut Config, desktop: Desktop, enabled: bool) {
    config
        .tray
        .autostart
        .desktops
        .insert(desktop_config_key(desktop).into(), enabled);
}

/// Enabled `OnlyShowIn` entries from config, skipping unsupported desktops.
pub fn enabled_autostart_only_show_in(
    desktops: &impl std::borrow::Borrow<HashMap<String, bool>>,
) -> Vec<&'static str> {
    let desktops = desktops.borrow();
    let mut tokens = Vec::new();
    for (key, enabled) in desktops {
        if !enabled {
            continue;
        }
        if let Some(desktop) = desktop_from_config_key(key) {
            if tray_autostart_available(desktop) {
                tokens.push(desktop_only_show_in(desktop));
            }
        }
    }
    tokens.sort_unstable();
    tokens.dedup();
    tokens
}

fn desktop_from_config_key(key: &str) -> Option<Desktop> {
    match key {
        "cosmic" => Some(Desktop::Cosmic),
        "gnome" => Some(Desktop::Gnome),
        "unity" => Some(Desktop::Unity),
        "budgie" => Some(Desktop::Budgie),
        "kde" => Some(Desktop::Kde),
        "xfce" => Some(Desktop::Xfce),
        "lxde" => Some(Desktop::Lxde),
        "lxqt" => Some(Desktop::Lxqt),
        "mate" => Some(Desktop::Mate),
        "cinnamon" => Some(Desktop::Cinnamon),
        "deepin" => Some(Desktop::Deepin),
        "sway" => Some(Desktop::Sway),
        "hyprland" => Some(Desktop::Hyprland),
        "enlightenment" => Some(Desktop::Enlightenment),
        "awesome" => Some(Desktop::Awesome),
        "fluxbox" => Some(Desktop::Fluxbox),
        "trinity" => Some(Desktop::Trinity),
        "lingmo" => Some(Desktop::Lingmo),
        "unknown" => Some(Desktop::Unknown),
        _ => None,
    }
}

/// Path to the managed autostart desktop entry under `XDG_CONFIG_HOME`.
pub fn autostart_desktop_file_path(config_home: &Path) -> PathBuf {
    config_home.join("autostart").join(AUTOSTART_FILENAME)
}

/// Build the XDG autostart desktop entry contents.
pub fn build_autostart_desktop_entry(exec: &str, only_show_in: &[&str]) -> String {
    let only_show_in_line = if only_show_in.is_empty() {
        String::new()
    } else {
        format!("OnlyShowIn={};\n", only_show_in.join(";"))
    };

    format!(
        "# {GENERATED_MARKER} — do not edit; change tray.autostart in config.json\n\
         [Desktop Entry]\n\
         Type=Application\n\
         Name=walls tray\n\
         Comment=Wallpaper rotation system tray\n\
         Exec={exec}\n\
         Icon=walls\n\
         Terminal=false\n\
         Categories=Utility;\n\
         X-GNOME-Autostart-enabled=true\n\
         {only_show_in_line}\
         Hidden=false\n"
    )
}

fn has_graphical_session(opts: &AutostartSyncOpts<'_>) -> bool {
    !matches!(
        session_type_from_env(opts.xdg_session_type, opts.wayland_display, opts.display),
        crate::tray::SessionType::Unknown
    )
}

fn should_write_autostart(opts: &AutostartSyncOpts<'_>) -> Option<Vec<&'static str>> {
    if !has_graphical_session(opts) {
        return None;
    }

    let only_show_in = enabled_autostart_only_show_in(&opts.config.tray.autostart.desktops);
    if only_show_in.is_empty() {
        return None;
    }

    Some(only_show_in)
}

/// Sync tray autostart from live environment.
pub fn sync_tray_autostart(config: &Config) -> anyhow::Result<AutostartSyncOutcome> {
    sync_tray_autostart_mode(config, false)
}

/// Preview tray autostart sync from live environment without writing files.
pub fn dry_run_tray_autostart_sync(config: &Config) -> anyhow::Result<AutostartSyncOutcome> {
    sync_tray_autostart_mode(config, true)
}

fn sync_tray_autostart_mode(
    config: &Config,
    dry_run: bool,
) -> anyhow::Result<AutostartSyncOutcome> {
    let config_home = config_home_dir()?;
    let tray_bin = resolve_binary(BinResolveOpts {
        env_var: std::env::var("WALLS_TRAY_BIN").ok().as_deref(),
        current_exe: std::env::current_exe().ok().as_deref(),
        sibling_name: "walls-tray",
        build_default: None,
        path_fallback: "walls-tray",
    });

    let xdg_current_desktop = std::env::var("XDG_CURRENT_DESKTOP").ok();
    let xdg_session_desktop = std::env::var("XDG_SESSION_DESKTOP").ok();
    let desktop_startup_id = std::env::var("DESKTOP_STARTUP_ID").ok();
    let xdg_session_type = std::env::var("XDG_SESSION_TYPE").ok();
    let wayland_display = std::env::var("WAYLAND_DISPLAY").ok();
    let display = std::env::var("DISPLAY").ok();
    let opts = AutostartSyncOpts {
        config_home: &config_home,
        tray_bin,
        config,
        xdg_current_desktop: xdg_current_desktop.as_deref(),
        xdg_session_desktop: xdg_session_desktop.as_deref(),
        desktop_startup_id: desktop_startup_id.as_deref(),
        xdg_session_type: xdg_session_type.as_deref(),
        wayland_display: wayland_display.as_deref(),
        display: display.as_deref(),
    };
    sync_tray_autostart_with_mode(&opts, dry_run)
}

/// Sync tray autostart with explicit paths/env (testable).
pub fn sync_tray_autostart_with(
    opts: &AutostartSyncOpts<'_>,
) -> anyhow::Result<AutostartSyncOutcome> {
    sync_tray_autostart_with_mode(opts, false)
}

/// Preview tray autostart sync with explicit paths/env without writing files.
pub fn dry_run_tray_autostart_sync_with(
    opts: &AutostartSyncOpts<'_>,
) -> anyhow::Result<AutostartSyncOutcome> {
    sync_tray_autostart_with_mode(opts, true)
}

fn sync_tray_autostart_with_mode(
    opts: &AutostartSyncOpts<'_>,
    dry_run: bool,
) -> anyhow::Result<AutostartSyncOutcome> {
    let path = autostart_desktop_file_path(opts.config_home);

    let Some(only_show_in) = should_write_autostart(opts) else {
        if path.exists() && is_managed_autostart_file(&path)? {
            if dry_run {
                return Ok(AutostartSyncOutcome::WouldRemove { path });
            }
            fs::remove_file(&path)?;
            return Ok(AutostartSyncOutcome::Removed);
        }
        return Ok(AutostartSyncOutcome::Skipped {
            reason: "tray autostart disabled".into(),
        });
    };

    if !opts.tray_bin.is_file() {
        return Ok(AutostartSyncOutcome::Skipped {
            reason: format!("walls-tray not found at {}", opts.tray_bin.display()),
        });
    }

    let exec = opts.tray_bin.display().to_string();
    let contents = build_autostart_desktop_entry(&exec, &only_show_in);
    if dry_run {
        return Ok(AutostartSyncOutcome::WouldWrite { path });
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let tmp = path.with_extension("desktop.tmp");
    {
        let mut file = fs::File::create(&tmp)?;
        file.write_all(contents.as_bytes())?;
        file.sync_all()?;
    }
    fs::rename(tmp, &path)?;
    Ok(AutostartSyncOutcome::Written)
}

/// Whether the on-disk autostart entry disagrees with config.
pub fn autostart_out_of_sync(opts: &AutostartSyncOpts<'_>) -> bool {
    let path = autostart_desktop_file_path(opts.config_home);
    let want_write = should_write_autostart(opts).is_some();

    match (want_write, path.exists()) {
        (false, false) => false,
        (true, false) => true,
        (false, true) => is_managed_autostart_file(&path).unwrap_or(false),
        (true, true) => {
            let Ok(text) = fs::read_to_string(&path) else {
                return true;
            };
            if !text.contains(GENERATED_MARKER) {
                return false;
            }
            let Some(only_show_in) = should_write_autostart(opts) else {
                return true;
            };
            let expected =
                build_autostart_desktop_entry(&opts.tray_bin.display().to_string(), &only_show_in);
            text != expected
        }
    }
}

fn is_managed_autostart_file(path: &Path) -> anyhow::Result<bool> {
    let text = fs::read_to_string(path)?;
    Ok(text.contains(GENERATED_MARKER))
}

fn config_home_dir() -> anyhow::Result<PathBuf> {
    if let Ok(dir) = std::env::var("XDG_CONFIG_HOME") {
        if !dir.is_empty() {
            return Ok(PathBuf::from(dir));
        }
    }
    let home = std::env::var("HOME")?;
    Ok(PathBuf::from(home).join(".config"))
}

/// Label for the current desktop in TUI autostart field.
pub fn tray_autostart_field_label(desktop: Desktop) -> String {
    let name = crate::tray::desktop_display_name(desktop);
    if tray_autostart_available(desktop) {
        format!("Tray autostart ({name})")
    } else {
        format!("Tray autostart ({name}, unavailable)")
    }
}

/// Current desktop for autostart configuration.
pub fn current_autostart_desktop() -> Desktop {
    detect_desktop()
}
